spring:
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
  application:
    name: banking-app
  datasource:
    url: jdbc:postgresql://localhost:5432/bankdb
    username: postgres
    password: 1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

